export const properties = [
  {
    id: 1,
    image: "/images/مغاسل_رخام/مغاسل_رخام.jpeg",
    name: " مغسلة رخام ستتواريو ايطالي ابيض مع مرايا وخشب",
    square: "155 سم",
    beds: 4,
    baths: 4,
    price: 400,
    rating: 5.0,
    detail: [
      "/images/property/single/1.jpg",
      "/images/property/single/2",
      "/images/property/single/3",
      "/images/property/single/4.jpg",
      "/images/property/single/5.jpg",
    ],
  },
  {
    id: 2,
    image: "/images/property/2.jpg",
    name: "59345 STONEWALL DR, Plaquemine, LA 70764, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
    detail: [
      "/images/property/single/1.jpg",
      "/images/property/single/2",
      "/images/property/single/3",
      "/images/property/single/4.jpg",
      "/images/property/single/5.jpg",
    ],
  },
  {
    id: 3,
    image: "/images/property/2.jpg",
    name: "3723 SANDBAR DR, Addis, LA 70710, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
    detail: [
      "/images/property/single/1.jpg",
      "/images/property/single/2",
      "/images/property/single/3",
      "/images/property/single/4.jpg",
      "/images/property/single/5.jpg",
    ],
  },
  {
    id: 4,
    image: "/images/property/2.jpg",
    name: "Lot 21 ROYAL OAK DR, Prairieville, LA 70769, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
    detail: [
      "/images/property/single/1.jpg",
      "/images/property/single/2",
      "/images/property/single/3",
      "/images/property/single/4.jpg",
      "/images/property/single/5.jpg",
    ],
  },
  {
    id: 5,
    image: "/images/property/2.jpg",
    name: "710 BOYD DR, Unit #1102, Baton Rouge, LA 70808, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
    detail: [
      "/images/property/single/1.jpg",
      "/images/property/single/2",
      "/images/property/single/3",
      "/images/property/single/4.jpg",
      "/images/property/single/5.jpg",
    ],
  },
  {
    id: 6,
    image: "/images/property/2.jpg",
    name: "5133 MCLAIN WAY, Baton Rouge, LA 70809, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
    detail: [
      "/images/property/single/1.jpg",
      "/images/property/single/2",
      "/images/property/single/3",
      "/images/property/single/4.jpg",
      "/images/property/single/5.jpg",
    ],
  },
];
export const propertiesDetails = [
  {
    id: 1,
    image: "/images/property/1.jpg",
    name: "مغسلة رخام كريم مارفل",
    square: 9999999,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
  },
  {
    id: 2,
    image: "/images/property/2.jpg",
    name: "59345 STONEWALL DR, Plaquemine, LA 70764, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
  },
  {
    id: 3,
    image: "/images/property/3.jpg",
    name: "3723 SANDBAR DR, Addis, LA 70710, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
  },
  {
    id: 4,
    image: "/images/property/4.jpg",
    name: "Lot 21 ROYAL OAK DR, Prairieville, LA 70769, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
  },
  {
    id: 5,
    image: "/images/property/5.jpg",
    name: "710 BOYD DR, Unit #1102, Baton Rouge, LA 70808, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
  },
  {
    id: 6,
    image: "/images/property/6.jpg",
    name: "5133 MCLAIN WAY, Baton Rouge, LA 70809, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
  },
  {
    id: 7,
    image: "/images/property/7.jpg",
    name: "2141 Fiero Street, Baton Rouge, LA 70808",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5,
  },
  {
    id: 8,
    image: "/images/property/8.jpg",
    name: "9714 Inniswold Estates Ave, Baton Rouge, LA 70809",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5,
  },
  {
    id: 9,
    image: "/images/property/9.jpg",
    name: "1433 Beckenham Dr, Baton Rouge, LA 70808, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5,
  },
  {
    id: 10,
    image: "/images/property/10.jpg",
    name: "1574 Sharlo Ave, Baton Rouge, LA 70820, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5,
  },
  {
    id: 11,
    image: "/images/property/11.jpg",
    name: "2528 BOCAGE LAKE DR, Baton Rouge, LA 70809, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5,
  },
  {
    id: 11,
    image: "/images/property/12.jpg",
    name: "1533 NICHOLSON DR, Baton Rouge, LA 70802, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5,
  },
];
export const blogList = [
  {
    id: 1,
    title: "Skills That You Can Learn In The Real Estate Market",
    date: "3rd March, 2023",
    type: "Industrial",
    image: "/images/property/1.jpg",
  },
  {
    id: 2,
    title: "Learn The Truth About Real Estate Industry",
    date: "3rd March, 2023",
    type: "Industrial",
    image: "/images/property/2.jpg",
  },
  {
    id: 3,
    title: "10 Quick Tips About Business Development",
    date: "3rd March, 2023",
    type: "Industrial",
    image: "/images/property/3.jpg",
  },
  {
    id: 4,
    title: "14 Common Misconceptions About Business Development",
    date: "3rd March, 2023",
    type: "Industrial",
    image: "/images/property/4.jpg",
  },
  {
    id: 5,
    title: "10 Things Your Competitors Can Teach You About Real Estate",
    date: "3rd March, 2023",
    type: "Industrial",
    image: "/images/property/5.jpg",
  },
  {
    id: 6,
    title: "Why We Love Real Estate",
    date: "3rd March, 2023",
    type: "Industrial",
    image: "/images/property/6.jpg",
  },
  {
    id: 7,
    title: "Skills That You Can Learn In The Real Estate Market",
    date: "3rd March, 2023",
    type: "Industrial",
    image: "/images/property/6.jpg",
  },
  {
    id: 8,
    title: "Learn The Truth About Real Estate Industry",
    date: "3rd March, 2023",
    type: "Industrial",
    image: "/images/property/5.jpg",
  },
  {
    id: 9,
    title: "10 Quick Tips About Business Development",
    date: "3rd March, 2023",
    type: "Industrial",
    image: "/images/property/4.jpg",
  },
  {
    id: 10,
    title: "14 Common Misconceptions About Business Development",
    date: "3rd March, 2023",
    type: "Industrial",
    image: "/images/property/3.jpg",
  },
  {
    id: 11,
    title: "10 Things Your Competitors Can Teach You About Real Estate",
    date: "3rd March, 2023",
    type: "Industrial",
    image: "/images/property/2.jpg",
  },
  {
    id: 12,
    title: "Why We Love Real Estate",
    date: "3rd March, 2023",
    type: "Industrial",
    image: "/images/property/1.jpg",
  },
];
